import { StyleSheet } from 'react-native';
import { AppColors } from '../../../../config/Colors';
import {
  responsiveHeight,
  responsiveWidth,
  responsiveFontSize,
} from '../../../../globalFunctions/Resposive_Dimensions';

export default StyleSheet.create({
  tabsRow: {
    flexDirection: 'row',
    gap: responsiveWidth(2.5),
    marginVertical: responsiveHeight(1.5)
    // paddingTop: responsiveHeight(2),
    // paddingBottom: responsiveHeight(1.5),
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: responsiveWidth(3.5),
    height: responsiveHeight(7),
    borderRadius: responsiveHeight(1.2),
    gap: responsiveWidth(2),
    backgroundColor: '#EFEFEF',
    marginTop: 'auto',
  },

  inputIcon: {
    padding: responsiveWidth(1),
  },
  chatInput: {
    flex: 1,
    color: AppColors.black,
    fontSize: responsiveFontSize(1.7),
    padding: 0,
    height: '100%',
  },
  tabPill: {
    backgroundColor: '#D8D8D8',
    borderRadius: responsiveHeight(0.7),
    paddingHorizontal: responsiveWidth(4),
    paddingVertical: responsiveHeight(1),
  },
  tabPillActive: {
    backgroundColor: AppColors.textWhite,
    borderColor: AppColors.textWhite,
  },
  tabPillText: {
    color: '#726E6D',
    fontSize: responsiveFontSize(1.5),
    fontWeight: '500',
  },
  tabPillTextActive: {
    color: AppColors.darkBg,
    fontWeight: '700',
  },
  scroll: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: responsiveHeight(2),
  },
  sectionTitle: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(2.2),
    fontWeight: '700',
    // marginTop: responsiveHeight(1.5),
    // marginBottom: responsiveHeight(0.6),
  },
  sectionSubtitle: {
    color: AppColors.white,
    fontSize: responsiveFontSize(1.45),
    marginBottom: responsiveHeight(1.8),
  },
  dateRow: {
    // flexDirection: 'row',
    // justifyContent: 'flex-end',
    // marginBottom: responsiveHeight(1.5),
  },
  dateBtn: {
    backgroundColor: AppColors.textWhite,
    color: AppColors.darkBg,
    borderRadius: responsiveHeight(0.7),
    paddingHorizontal: responsiveWidth(3),
    paddingVertical: responsiveHeight(0.7),
    fontWeight: '700',
    fontSize: responsiveFontSize(1.3),
    overflow: 'hidden',
  },
  sectionBlock: {
    marginBottom: responsiveHeight(2),
  },
  sectionBlockLabel: {
    color: AppColors.textWhite,
    fontWeight: '700',
    fontSize: responsiveFontSize(1.6),
  },
  scriptureBox: {
    backgroundColor: AppColors.textWhite,
    borderRadius: responsiveHeight(0.7),
    padding: responsiveWidth(3),
    marginBottom: responsiveHeight(1.2),
  },
  scriptureRef: {
    color: AppColors.darkBg,
    fontWeight: '600',
    fontSize: responsiveFontSize(1.4),
    marginBottom: responsiveHeight(0.3),
  },
  scriptureText: {
    color: AppColors.darkBg,
    fontSize: responsiveFontSize(1.4),
    marginBottom: responsiveHeight(0.3),
  },
  scriptureSource: {
    color: AppColors.darkBg,
    fontSize: responsiveFontSize(1.1),
    fontStyle: 'italic',
    fontWeight: '600',
  },
  sectionBlockText: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(1.45),
    lineHeight: responsiveFontSize(2.1),
  },
  ctaRow: {
    flexDirection: 'row',
    gap: responsiveWidth(3),
    marginTop: responsiveHeight(2.5),
    marginBottom: responsiveHeight(2.5),
    justifyContent: 'space-between',
  },
  ctaBtn: {
    flex: 1,
    backgroundColor: AppColors.textWhite,
    borderRadius: responsiveHeight(0.7),
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: responsiveHeight(1.7),
    marginHorizontal: responsiveWidth(1),
  },
  ctaBtnText: {
    color: AppColors.darkBg,
    fontWeight: '700',
    fontSize: responsiveFontSize(1.7),
  },
  emptyTabContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: responsiveWidth(4.5),
  },
  emptyTabIcon: {
    marginBottom: responsiveHeight(2.5),
  },
  emptyTabIconColor: {
    color: AppColors.textWhite,
  },
  emptyTabText: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(1.7),
    textAlign: 'center',
    fontWeight: '400',
  },
  emptyCard: {
    borderWidth: 1,
    borderColor: AppColors.textWhite,
    borderRadius: responsiveHeight(1),
    paddingVertical: responsiveHeight(4),
    paddingHorizontal: responsiveWidth(4),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: responsiveHeight(1.5),
    width: '100%',
  },
  emptyCardIcon: {
    marginBottom: responsiveHeight(1.2),
  },
  emptyCardText: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(1.6),
    textAlign: 'center',
  },
  borderedCardSubtitle: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(1.4),
    textAlign: 'center',
    marginBottom: responsiveHeight(1.2),
    paddingHorizontal: responsiveWidth(2),
  },
  startSoapBtn: {
    width: '100%',
    paddingVertical: responsiveHeight(0.7),
    marginTop: responsiveHeight(0.6),
  },
  searchRow: {
    marginTop: responsiveHeight(1),
    paddingHorizontal: responsiveWidth(0),
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: AppColors.textWhite,
    borderRadius: responsiveHeight(1),
    paddingVertical: responsiveHeight(1.1),
    paddingHorizontal: responsiveWidth(3.5),
  },
  searchText: {
    color: '#9E9E9E',
    marginLeft: responsiveWidth(3),
    fontSize: responsiveFontSize(1.4),
  },
  searchBoxOverride: {
    backgroundColor: AppColors.textWhite,
    borderWidth: 0,
    paddingVertical: responsiveHeight(1.2),
    paddingHorizontal: responsiveWidth(3),
  },
  searchInputText: {
    color: '#9E9E9E',
    fontSize: responsiveFontSize(1.45),
  },
  planCard: {
    borderWidth: 1,
    borderColor: AppColors.textWhite,
    borderRadius: responsiveHeight(1),
    padding: responsiveWidth(4),
    marginBottom: responsiveHeight(1.5),
    width: '100%',
  },
  planCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: responsiveHeight(0.8),
  },
  planCardTitle: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(1.7),
    fontWeight: '700',
    flex: 1,
    marginRight: responsiveWidth(2),
  },
  planCardTag: {
    color: AppColors.textWhite,
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: responsiveWidth(3),
    paddingVertical: responsiveHeight(0.6),
    borderRadius: responsiveHeight(0.8),
    fontSize: responsiveFontSize(1.1),
    fontWeight: '700',
  },
  planCardDesc: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(1.35),
    marginBottom: responsiveHeight(0.8),
  },
  planMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: responsiveHeight(0.4),
  },
  planMetaText: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(1.25),
  },
  progressLabel: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(1.1),
    marginTop: responsiveHeight(0.6),
    marginBottom: responsiveHeight(0.4),
  },
  progressBarContainer: {
    width: '100%',
    height: responsiveHeight(1.2),
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: responsiveHeight(1),
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: AppColors.textWhite,
  },
  planCTA: {
    marginTop: responsiveHeight(1.1),
    width: '100%',
    paddingVertical: responsiveHeight(0.9),
  },
  sectionLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: responsiveHeight(1.5),
  },
  sectionLabelBox: {
    width: responsiveHeight(3.2),
    height: responsiveHeight(3.2),
    borderRadius: responsiveHeight(3),
    backgroundColor: AppColors.textWhite,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: responsiveWidth(2.2),
  },
  sectionLabelLetter: {
    color: AppColors.darkBg,
    fontWeight: '700',
    fontSize: responsiveFontSize(1.7),
  },
  askFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: AppColors.textWhite,
    paddingTop: responsiveHeight(1),
    paddingBottom: responsiveHeight(2),
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.08)',
  },
  suggestionsRow: {
    marginBottom: responsiveHeight(0.6),
  },
  suggestionPill: {
    backgroundColor: '#F0F0F0',
    paddingHorizontal: responsiveWidth(3),
    paddingVertical: responsiveHeight(0.6),
    borderRadius: responsiveHeight(1),
    marginRight: responsiveWidth(2),
  },
  suggestionText: {
    color: '#6B6B6B',
    fontSize: responsiveFontSize(1.4),
  },
  askInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: responsiveWidth(3.5),
  },
  askInputBox: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 0,
    paddingVertical: responsiveHeight(1.2),
    paddingHorizontal: responsiveWidth(3),
  },
  askInputText: {
    color: '#333333',
    fontSize: responsiveFontSize(1.6),
  },
  attachmentBtn: {
    paddingLeft: responsiveWidth(3),
  },
  sendBtn: {
    // backgroundColor: AppColors.textWhite,
    // marginLeft: responsiveWidth(2),
    padding: responsiveHeight(1.1),
    borderRadius: responsiveHeight(1.2),
    alignItems: 'center',
    justifyContent: 'center',
  },
});
