import { StyleSheet } from 'react-native';
import { AppColors } from '../../../../config/Colors';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from '../../../../globalFunctions/Resposive_Dimensions';

export default StyleSheet.create({
  screen: {
    paddingHorizontal: responsiveWidth(4.5),
  },
  summaryCard: {
    marginTop: responsiveHeight(1.5),
    padding: responsiveWidth(4),
    borderRadius: responsiveHeight(1.6),
    backgroundColor: AppColors.cardBg,
    borderWidth: 1,
    borderColor: AppColors.cardBorder,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  summaryEyebrow: {
    color: AppColors.textMuted,
    fontSize: responsiveFontSize(1.35),
    marginBottom: responsiveHeight(0.5),
  },
  summaryTitle: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(2.1),
    fontWeight: '700',
  },
  composeButton: {
    width: responsiveWidth(11),
    height: responsiveWidth(11),
    borderRadius: responsiveWidth(5.5),
    backgroundColor: AppColors.textWhite,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchRow: {
    marginTop: responsiveHeight(1.8),
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: responsiveWidth(2.5),
    borderRadius: responsiveHeight(1.2),
    backgroundColor: AppColors.inputBg,
    borderWidth: 1,
    borderColor: AppColors.inputBorder,
    paddingHorizontal: responsiveWidth(4),
    paddingVertical: responsiveHeight(1.4),
  },
  searchInput: {
    flex: 1,
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(1.75),
    padding: 0,
  },
  filterRow: {
    paddingTop: responsiveHeight(1.7),
    gap: responsiveWidth(2.5),
    paddingBottom: responsiveHeight(0.8),
  },
  filterChip: {
    borderRadius: responsiveHeight(2.5),
    borderWidth: 1,
    borderColor: AppColors.inputBorder,
    paddingHorizontal: responsiveWidth(4),
    paddingVertical: responsiveHeight(0.9),
    backgroundColor: AppColors.transparent,
  },
  filterChipActive: {
    backgroundColor: AppColors.textWhite,
    borderColor: AppColors.textWhite,
  },
  filterText: {
    color: AppColors.textMuted,
    fontSize: responsiveFontSize(1.45),
    fontWeight: '600',
  },
  filterTextActive: {
    color: AppColors.darkBg,
  },
  list: {
    flex: 1,
    marginTop: responsiveHeight(0.4),
  },
  listContent: {
    paddingBottom: responsiveHeight(3),
    gap: responsiveHeight(1.3),
  },
  chatCard: {
    borderRadius: responsiveHeight(1.6),
    borderWidth: 1,
    borderColor: AppColors.cardBorder,
    backgroundColor: AppColors.cardBg,
    padding: responsiveWidth(4),
    flexDirection: 'row',
    gap: responsiveWidth(3.5),
  },
  avatarWrap: {
    position: 'relative',
    width: responsiveWidth(13),
    height: responsiveWidth(13),
  },
  avatarRing: {
    width: '100%',
    height: '100%',
    borderRadius: responsiveWidth(6.5),
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.35)',
    padding: responsiveWidth(0.7),
  },
  avatarInner: {
    flex: 1,
    borderRadius: responsiveWidth(6),
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallback: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(2.2),
    fontWeight: '700',
  },
  onlineDot: {
    position: 'absolute',
    right: responsiveWidth(0.3),
    bottom: responsiveWidth(0.3),
    width: responsiveWidth(3.2),
    height: responsiveWidth(3.2),
    borderRadius: responsiveWidth(1.6),
    backgroundColor: AppColors.checkGreen,
    borderWidth: 2,
    borderColor: AppColors.cardBg,
  },
  chatMeta: {
    flex: 1,
    justifyContent: 'space-between',
  },
  chatMetaTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: responsiveWidth(3),
  },
  nameWrap: {
    flex: 1,
  },
  chatName: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(1.85),
    fontWeight: '700',
  },
  chatRole: {
    color: AppColors.textMuted,
    fontSize: responsiveFontSize(1.35),
    marginTop: responsiveHeight(0.25),
  },
  chatTime: {
    color: AppColors.textMuted,
    fontSize: responsiveFontSize(1.3),
    marginTop: responsiveHeight(0.2),
  },
  chatMetaBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: responsiveWidth(3),
    marginTop: responsiveHeight(1),
  },
  chatMessage: {
    flex: 1,
    color: AppColors.textMuted,
    fontSize: responsiveFontSize(1.45),
    lineHeight: responsiveFontSize(2.1),
  },
  unreadBadge: {
    minWidth: responsiveWidth(6),
    height: responsiveWidth(6),
    paddingHorizontal: responsiveWidth(1.5),
    borderRadius: responsiveWidth(3),
    backgroundColor: AppColors.textWhite,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unreadText: {
    color: AppColors.darkBg,
    fontSize: responsiveFontSize(1.25),
    fontWeight: '700',
  },
  emptyCard: {
    marginTop: responsiveHeight(2),
    padding: responsiveWidth(5),
    borderRadius: responsiveHeight(1.5),
    backgroundColor: AppColors.cardBg,
    borderWidth: 1,
    borderColor: AppColors.cardBorder,
    alignItems: 'center',
  },
  emptyTitle: {
    color: AppColors.textWhite,
    fontSize: responsiveFontSize(1.8),
    fontWeight: '700',
  },
  emptyText: {
    color: AppColors.textMuted,
    fontSize: responsiveFontSize(1.45),
    lineHeight: responsiveFontSize(2.1),
    textAlign: 'center',
    marginTop: responsiveHeight(0.6),
  },
});